<a href="https://colab.research.google.com/github/abdul12013/LERN/blob/main/missingVal_sckite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

finding missing value using skite-learn

In [2]:
import pandas as pd
import seaborn as snd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("/content/1_1_2023_general.csv")
data.head()

,connect_price,created_on,tz_date,duration,engagement,freelancers_to_hire,amount_amount,hourly_rate,type,job_ts,...,total_freelancers_to_hire,uid,client_company_org_uid,client_payment_verification_status,client_total_feedback,client_total_reviews,client_total_spent,client_location_country,occupations_category_pref_label,occupations_oservice_pref_label
0,6,2023-01-01T17:33:29Z,2023-01-01T17:33:29Z,More than 6 months,30+ hrs/week,1,NaN,30.0,hourly,1672594409972,...,1,1609603731584323584,1608471451601813505,1.0,0.0,0,0.00,Canada,Translation,Live Interpretation
1,2,2023-01-01T17:38:19Z,2023-01-01T17:38:19Z,Less than 1 month,NaN,1,30.0,NaN,fixed_budget,1672594699447,...,1,1609604946319015936,826145256945999872,1.0,5.0,20,3817.42,United States,Design & Creative,Cartoons & Comics
2,4,2023-01-01T17:38:17Z,2023-01-01T17:38:17Z,Less than 1 month,NaN,1,100.0,NaN,fixed_budget,1672594697764,...,1,1609604938732384256,1608183213743005696,1.0,5.0,1,50.00,United States,Design & Creative,Graphic Design
3,2,2023-01-01T17:38:03Z,2023-01-01T17:38:03Z,3 to 6 months,NaN,1,500.0,NaN,fixed_budget,1672594683145,...,1,1609601320662839296,1609595819727970305,2.0,0.0,0,0.00,Sweden,Sales & Marketing,Social Media Marketing
4,4,2023-01-01T17:37:54Z,2023-01-01T17:37:54Z,1 to 3 months,NaN,5,350.0,NaN,fixed_budget,1672594674356,...,5,1609604840953905152,1609320405007642625,1.0,0.0,0,0.00,United Kingdom,Sales & Marketing,Telemarketing

In [4]:
data.isnull().sum()

connect_price                            0
created_on                               0
tz_date                                  0
duration                                 0
engagement                            2191
freelancers_to_hire                      0
amount_amount                         2804
hourly_rate                           3205
type                                     0
job_ts                                   0
proposals_tier                           0
published_on                             0
renewed_on                            4915
tier                                     0
title                                    0
total_freelancers_to_hire                0
uid                                      0
client_company_org_uid                   0
client_payment_verification_status     113
client_total_feedback                    0
client_total_reviews                     0
client_total_spent                       0
client_location_country                  0
occupations_category_pref_label          0
occupations_oservice_pref_label          0
dtype: int64

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4995 entries, 0 to 4994
Data columns (total 25 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   connect_price                       4995 non-null   int64
 1   created_on                          4995 non-null   object
 2   tz_date                             4995 non-null   object
 3   duration                            4995 non-null   object
 4   engagement                          2804 non-null   object
 5   freelancers_to_hire                 4995 non-null   int64
 6   amount_amount                       2191 non-null   float64
 7   hourly_rate                         1790 non-null   float64
 8   type                                4995 non-null   object
 9   job_ts                              4995 non-null   int64
 10  proposals_tier                      4995 non-null   object
 11  published_on                        4995 non-null   object
 12  renewed_on                          80 non-null     object
 13  tier                                4995 non-null   object
 14  title                               4995 non-null   object
 15  total_freelancers_to_hire           4995 non-null   int64
 16  uid                                 4995 non-null   int64
 17  client_company_org_uid              4995 non-null   int64
 18  client_payment_verification_status  4882 non-null   float64
 19  client_total_feedback               4995 non-null   float64
 20  client_total_reviews                4995 non-null   int64
 21  client_total_spent                  4995 non-null   float64
 22  client_location_country             4995 non-null   object
 23  occupations_category_pref_label     4995 non-null   object
 24  occupations_oservice_pref_label     4995 non-null   object
dtypes: float64(5), int64(7), object(13)
memory usage: 975.7+ KB

In [8]:
data.select_dtypes(include='float64').columns

Index(['amount_amount', 'hourly_rate', 'client_payment_verification_status',
       'client_total_feedback', 'client_total_spent'],
      dtype='object')

Filling missing value using skite learn

In [9]:
from sklearn.impute import SimpleImputer

In [11]:
si=SimpleImputer(strategy='mean')
arr=si.fit_transform(data[['amount_amount', 'hourly_rate', 'client_payment_verification_status',
       'client_total_feedback', 'client_total_spent']])

In [12]:
updated=pd.DataFrame(arr,columns=data.select_dtypes(include='float64').columns)

In [13]:
updated.head()

,amount_amount,hourly_rate,client_payment_verification_status,client_total_feedback,client_total_spent
0,633.11319,30.000000,1.0,0.0,0.00
1,30.00000,25.764385,1.0,5.0,3817.42
2,100.00000,25.764385,1.0,5.0,50.00
3,500.00000,25.764385,2.0,0.0,0.00
4,350.00000,25.764385,1.0,0.0,0.00

In [14]:
updated.isnull().sum()

amount_amount                         0
hourly_rate                           0
client_payment_verification_status    0
client_total_feedback                 0
client_total_spent                    0
dtype: int64